server.port=8101
spring.application.name=audit-service
eureka.instance.hostname=localhost
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.config.import=optional:configserver:http://localhost:8888
spring.data.mongodb.uri=mongodb+srv://blumbit_mongo:SlMXbn3ys4SAEEYE@clustermongo.oumji7s.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMongo