server.port=8102
spring.application.name=gateway-service
eureka.instance.hostname=localhost
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.gateway.routes[0].id=audit-service
spring.cloud.gateway.routes[0].uri=http://localhost:8101
spring.cloud.gateway.routes[0].predicates=Path=/audit-service/**
spring.cloud.gateway.routes[1].id=supermercado-service
spring.cloud.gateway.routes[1].uri=http://localhost:8100
spring.cloud.gateway.routes[1].predicates=Path=/supermercado-service/**